on:
  push:
    branches:
      - main
      - latest
      - next
  pull_request:
    branches:
      - main
      - latest
      - next
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm prettier --plugin=prettier-plugin-svelte -c .
      - run: pnpm tsc
      - run: pnpm eslint .
      - run: pnpm stylelint .
      - run: pnpm vitest run
      - run: pnpm build
      - run: pnpm --recursive --sequential run build
  release:
    needs: check
    if: github.ref == 'refs/heads/latest' || github.ref == 'refs/heads/next'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: node release/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: ''
          GIT_COMMITTER_EMAIL: ''
      - run: git fetch . ${{ github.ref }}:main
      - run: git push origin main
